language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements/python2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3* ]]; then pip install -r requirements/python3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then pip install -r requirements/python3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then pip install -r requirements/python3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then pip install -r requirements/python3.txt; fi
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install -e .
script:
  - nosetests -v -w ipwhois --include=online --exclude=stress --with-coverage --cover-package=ipwhois
after_success:
  - coveralls --rcfile=.coveragerc
  - codeclimate-test-reporter
